on:
  push:
    tags:
      - 'v**'
  workflow_dispatch:

name: Release

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/')"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install stable toolchain
        uses: actions-rs/toolchain@stable
      - name: cargo login
        run: cargo login ${{ secrets.CARGO_API_TOKEN }}
      - run: cargo publish
